steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west2-docker.pkg.dev/stockport-badminton-map/league-site/app:$COMMIT_SHA'
      - '-t'
      - 'europe-west2-docker.pkg.dev/stockport-badminton-map/league-site/app:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-west2-docker.pkg.dev/stockport-badminton-map/league-site/app'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'league-site'
      - '--image'
      - 'europe-west2-docker.pkg.dev/stockport-badminton-map/league-site/app:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'
      - '--project'
      - 'stockport-badminton-map'

images:
  - 'europe-west2-docker.pkg.dev/stockport-badminton-map/league-site/app:$COMMIT_SHA'
  - 'europe-west2-docker.pkg.dev/stockport-badminton-map/league-site/app:latest'
