-- Messer scorecard submission and result tracking
-- messer_scorecard: Draft submissions (captains submit results)
-- messer_result: Approved results (after Neil reviews and approves)

CREATE TABLE messer_scorecard (
  id                    SERIAL PRIMARY KEY,
  date                  TIMESTAMP,
  "homeTeam"            INTEGER NOT NULL,
  "awayTeam"            INTEGER NOT NULL,
  "homeMan1"            INTEGER,
  "homeMan2"            INTEGER,
  "homeLady1"           INTEGER,
  "homeLady2"           INTEGER,
  "awayMan1"            INTEGER,
  "awayMan2"            INTEGER,
  "awayLady1"           INTEGER,
  "awayLady2"           INTEGER,
  "FirstMixedhomeMan"   INTEGER,
  "FirstMixedhomeLady"  INTEGER,
  "FirstMixedawayMan"   INTEGER,
  "FirstMixedawayLady"  INTEGER,
  "SecondMixedhomeMan"  INTEGER,
  "SecondMixedhomeLady" INTEGER,
  "SecondMixedawayMan"  INTEGER,
  "SecondMixedawayLady" INTEGER,
  "ThirdMixedhomeMan"   INTEGER,
  "ThirdMixedhomeLady"  INTEGER,
  "ThirdMixedawayMan"   INTEGER,
  "ThirdMixedawayLady"  INTEGER,
  "Game1homeScore"      INTEGER,
  "Game1awayScore"      INTEGER,
  "Game2homeScore"      INTEGER,
  "Game2awayScore"      INTEGER,
  "Game3homeScore"      INTEGER,
  "Game3awayScore"      INTEGER,
  "Game4homeScore"      INTEGER,
  "Game4awayScore"      INTEGER,
  "Game5homeScore"      INTEGER,
  "Game5awayScore"      INTEGER,
  "Game6homeScore"      INTEGER,
  "Game6awayScore"      INTEGER,
  "Game7homeScore"      INTEGER,
  "Game7awayScore"      INTEGER,
  "Game8homeScore"      INTEGER,
  "Game8awayScore"      INTEGER,
  "Game9homeScore"      INTEGER,
  "Game9awayScore"      INTEGER,
  "Game10homeScore"     INTEGER,
  "Game10awayScore"     INTEGER,
  "Game11homeScore"     INTEGER,
  "Game11awayScore"     INTEGER,
  "Game12homeScore"     INTEGER,
  "Game12awayScore"     INTEGER,
  "Game13homeScore"     INTEGER,
  "Game13awayScore"     INTEGER,
  "Game14homeScore"     INTEGER,
  "Game14awayScore"     INTEGER,
  "Game15homeScore"     INTEGER,
  "Game15awayScore"     INTEGER,
  email                 VARCHAR(100),
  status                TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'submitted')),
  "created_at"          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at"          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messer_result (
  id                    SERIAL PRIMARY KEY,
  "messer_id"           INTEGER,
  date                  TIMESTAMP,
  "homeTeam"            INTEGER NOT NULL,
  "awayTeam"            INTEGER NOT NULL,
  "Game1homeScore"      INTEGER,
  "Game1awayScore"      INTEGER,
  "Game2homeScore"      INTEGER,
  "Game2awayScore"      INTEGER,
  "Game3homeScore"      INTEGER,
  "Game3awayScore"      INTEGER,
  "Game4homeScore"      INTEGER,
  "Game4awayScore"      INTEGER,
  "Game5homeScore"      INTEGER,
  "Game5awayScore"      INTEGER,
  "Game6homeScore"      INTEGER,
  "Game6awayScore"      INTEGER,
  "Game7homeScore"      INTEGER,
  "Game7awayScore"      INTEGER,
  "Game8homeScore"      INTEGER,
  "Game8awayScore"      INTEGER,
  "Game9homeScore"      INTEGER,
  "Game9awayScore"      INTEGER,
  "Game10homeScore"     INTEGER,
  "Game10awayScore"     INTEGER,
  "Game11homeScore"     INTEGER,
  "Game11awayScore"     INTEGER,
  "Game12homeScore"     INTEGER,
  "Game12awayScore"     INTEGER,
  "Game13homeScore"     INTEGER,
  "Game13awayScore"     INTEGER,
  "Game14homeScore"     INTEGER,
  "Game14awayScore"     INTEGER,
  "Game15homeScore"     INTEGER,
  "Game15awayScore"     INTEGER,
  "homeWins"            INTEGER,
  "awayWins"            INTEGER,
  status                TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  "created_at"          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "approved_at"         TIMESTAMP,
  FOREIGN KEY ("messer_id") REFERENCES messer(id)
);

CREATE INDEX idx_messer_scorecard_status ON messer_scorecard(status);
CREATE INDEX idx_messer_scorecard_homeTeam ON messer_scorecard("homeTeam");
CREATE INDEX idx_messer_result_status ON messer_result(status);
CREATE INDEX idx_messer_result_messer_id ON messer_result("messer_id");
